if has ('gui_running')
    set cursorline " highlight current line
endif
" set number    " display line number
set guioptions=l " scroll bar at left
set ru    " display status bar
set hls             " highlight searching keywords
set foldmethod=syntax
if has('gui_running')
set foldcolumn=4
endif
set foldlevel=3

set ts=4
set sts=4
set smarttab
set sw=4
set et
set nobackup
syntax on
filetype plugin indent on

" Vundle

set nocompatible              " be iMproved
" filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'
Bundle 'rizzatti/funcoo.vim'
Bundle 'rizzatti/dash.vim'

